"""
Qwen-only resume pass.

Fills ONLY the empty qwen_answer cells in results.csv for rows that already have
agent/judge results (from a SKIP_QWEN run). It does not touch or reprocess anything
else -- agents, judge verdicts, and rows that already have a Qwen answer are left
exactly as they are.

For each row needing a baseline:
  - qwen_answer         : generated by the Qwen baseline model
  - qwen_correct        : legacy semantic-similarity score (reference)
  - qwen_correct_judged : factual grade from the baseline-only judge (same JUDGE_MODEL)
All three are written together (atomically per row), so a row is only marked done when
its baseline is fully evaluated. Idempotent and resumable: if the Qwen or judge daily
quota is hit, it saves progress and exits; re-run after the quota resets to continue.

Run:  python qwen_pass.py
Note: keep the SAME judge model (Scout) as the SKIP_QWEN run for consistency; do not
flip USE_VALIDATION_JUDGE for this fill pass.
"""

import time

import pandas as pd
from sentence_transformers import SentenceTransformer

import main as m

CSV = "results.csv"


def _needs_qwen(row):
    """A row needs a Qwen answer iff it has none yet but has valid agent + judge results."""
    ans       = str(row.get("qwen_answer", "")).strip()
    has_answer = bool(ans) and ans.lower() != "nan"
    status    = str(row.get("judge_selection_status", "")).strip()
    judged    = status not in ("", "nan", "JUDGE_ERROR")
    agents_ok = (not str(row.get("answer_a", "")).startswith("ERROR:")
                 and not str(row.get("answer_b", "")).startswith("ERROR:"))
    return (not has_answer) and judged and agents_ok


def run():
    client = m.setup_groq_client()
    print(f"Qwen-only pass using judge model: {m.JUDGE_MODEL}")
    print("Loading embedding model (all-MiniLM-L6-v2)...")
    embedding_model = SentenceTransformer("all-MiniLM-L6-v2")
    print("Embedding model loaded.\n")

    df = pd.read_csv(CSV)
    todo = [i for i in df.index if _needs_qwen(df.loc[i].to_dict())]
    print(f"{len(todo)} of {len(df)} row(s) need a Qwen answer.")
    if not todo:
        print("Nothing to fill. Done.")
        return

    filled  = 0
    stopped = False
    for count, i in enumerate(todo, start=1):
        question     = str(df.at[i, "question"])
        ground_truth = str(df.at[i, "ground_truth"])
        print(f"Qwen fill {count}/{len(todo)} (row {i})...")

        try:
            qwen_answer  = m.get_qwen_baseline_answer(client, question)
            qwen_errored = qwen_answer.startswith("ERROR:") or qwen_answer == ""
            qwen_correct = m._qwen_similarity_fallback(qwen_answer, qwen_errored, ground_truth, embedding_model)
            if qwen_errored:
                qwen_correct_judged = False
            else:
                qwen_correct_judged = m.get_baseline_judge_evaluation(
                    client, question, qwen_answer, ground_truth, embedding_model
                )
        except m.DailyTokenLimitError as e:
            # Do NOT commit the current row -- leave it empty so it is retried on resume.
            stopped = True
            print(f"\n[STOP] Daily token limit (TPD) reached: {e}")
            print("Progress saved. Re-run after the quota resets to continue.")
            break

        # Commit all three cells together.
        df.at[i, "qwen_answer"]         = qwen_answer
        df.at[i, "qwen_correct"]        = qwen_correct
        df.at[i, "qwen_correct_judged"] = qwen_correct_judged
        filled += 1

        if filled % m.SAVE_EVERY == 0:
            df.to_csv(CSV, index=False, encoding="utf-8")
            print(f"  [Saved] {filled} filled so far -> {CSV}")

        time.sleep(m.DELAY_BETWEEN_QUESTIONS)

    df.to_csv(CSV, index=False, encoding="utf-8")
    remaining = sum(1 for i in df.index if _needs_qwen(df.loc[i].to_dict()))
    print(f"\nFilled {filled} row(s). {remaining} still pending.")
    if stopped or remaining:
        print("Re-run `python qwen_pass.py` after the quota resets to finish.")
    else:
        print("All Qwen baseline cells are now filled. Run `python main.py` (SKIP_QWEN=False) "
              "only if you want the full evaluation summary, or analyze results.csv directly.")


if __name__ == "__main__":
    run()
